language: go
go:
- 1.7
- 1.8
- tip
script: script/test
before_deploy:
- mkdir release
- GOOS=linux GOARCH=amd64 go build -o release/sg-restful-linux-amd64 -x -ldflags "-X main.Version=$TRAVIS_TAG" .
- GOOS=darwin GOARCH=amd64 go build -o release/sg-restful-darwin-amd64 -x -ldflags "-X main.Version=$TRAVIS_TAG" .
deploy:
  provider: releases
  api_key:
    secure: H5ggEfYqvTkLvdBox9oBq1+okz9O0U+eawsgEmP9MKGwauYMGnKzVWClH0ck/6BI/sbsZzAePF1ebKyLgrvDReZnB682iYcv7yjtJoPcv2KIUZiCf+4CTLrDHk6DlDAC8O5Jdkbj9roLL2stRj+MVgtTVrZ2Dd5hYMfLm5nhud98qORS2LGm/FsgfvvOwI7AZMQtdJSiw+N4X2Medjktb300afftKkreuY/MWcP9FaZvnZrxK2WL8rPVbNhLfOHk2NCewktVud+jsVWbUJ3X/3gA3mLhjo9q9nP1M8OO36IjzuRC12VdrwdL2H0dV8Zn+yEU9enF0iMahtWPLBTOicSOPRmDzTnTDtLDBUpVZwdNPLEOuiRbt8E48BmwBOXwtfjLIatK0O0DGqm7XYLVG3XQ3YMlJAW/OFV4V4Tkg2aFcslJ9wXMECzbdNRQuD0kSAGaFru/71fqioqpT5tsY4fKEOpSU/9F+Dj4+AyTwIT04ZgfvpavATh0eRNwrctathyPcfyI9cVn2aTUk65892u5Fe/xqhxCAZmm6rNfWrw1B2fbEntJhp6qQrG/zsEzb5VrIlK1ZZyaLw5NVcbhmlFnEeju4mfG4tLsZjZwYsLOzGf6dHZUK40J75RJaA8qSXvWFK/vkD1uI7rAEAGMKOC5b8CI0ZV0Z3h5oIHV6TI=
  file: 
    - release/sg-restful-linux-amd64
    - release/sg-restful-darwin-amd64
  on:
    repo: brandonvfx/sg-restful
    tags: true
    go: 1.8
